name: varsity
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - astroquery # from conda-forge channel
  - beautifulsoup4
  - astropy>=4.1
  - requests
  - tqdm
  - pandas
  - lightkurve >2.0
  - oktopus # from conda-forge channel
  - bokeh<2.3
  - jupyter
  - anaconda
  - celerite2
  - fitsio
  - ipython
  - seaborn
  - h5py
  - photutils # from conda-forge?
  - scikit-learn
  - scikit-image
  - yaml
  - astroplan
  - exoplanet # needed for orbit prediction
  - pip
  # - reproject # conda-forge
  ## We need SEP, but it is flakey with conda, so manually install:
  #   https://sep.readthedocs.io/en/v1.0.x/
  #   pip install --no-deps sep
  #
  #
  ## Also installed a custom Starfish:
  # obsidian at dust in ~/GitHub/Starfish on mix_model_omega2 [!]
  # $ python setup.py develop
  #
  # Need to install Montage: https://github.com/Caltech-IPAC/Montage
  - pip:
      - twisted
      #- mkl-random
      - emcee
      - corner
      # - muler # Install developer version
