Comments: varsity project
PCA:
  path: $varsity/sf/SOURCE/mORDER/libraries/Bobcat_PCA.hdf5
  priors:
  - [2.0, 0.0075]
  - [2.0, 0.75]
  threshold: 0.999
Phi: {l: 20.0, logAmp: -2.0, sigAmp: 1.0}
Phi_jump: {l: 0.25, logAmp: 0.01, sigAmp: 0.025}
Theta:
  Av: 0.0
  grid: [1350, 4.5]
  logOmega: 1.3
  vsini: 25.0
  vz: 0.0
Theta_jump:
  Av: 0.01
  grid: [3.0, 0.003]
  logOmega: 0.003
  vsini: 0.05
  vz: 0.05
Theta_priors: $varsity/sf/SOURCE/user_prior.py
cheb_degree: 4
cheb_jump: 0.0001
data:
  files: [$varsity/data/IGRINS/homoscedastic/SOURCE_mORDER.hdf5]
  grid_name: SonoraBobcat
  instruments: [IGRINS_K]
  orders: [0]
grid:
  buffer: 60.0
  hdf5_path: $varsity/sf/SOURCE/mORDER/libraries/Bobcat_grid.hdf5
  key_name: t{0:.0f}g{1:.1f}
  parname: [temp, logg]
  parrange:
  - [1000, 2400]
  - [3.25, 5.5]
  raw_path: /home/gully/libraries/raw/marley/
  wl_range: [12810, 13020]
name: marley_grid
outdir: output/
plotdir: plots/
region_params: {logAmp: -2.0, sigma: 7.0}
sigma_clip: 4.0
